package visual;

import java.awt.Dimension;
import control.*;
import entidades.*;
import javax.swing.JOptionPane;

public class NuevoTransporteWindow extends javax.swing.JFrame {

    /**
     * Creates new form NuevoTransporteWindow
     */
    MainWindow mainWindow;
    Datos datos;
    public NuevoTransporteWindow(Datos datos, MainWindow mainWindow) {        
        this.mainWindow = mainWindow;
        this.datos = datos;
        initComponents();
        /*
            una vez iniciado los componentes como se hizo la interfaz grafica
            con la herramienta del netbeans y tuve algunos problemas
            decidi posicionar y dar tamaño manualmente a los panales alternaitvos
            segun el tipo de transporte
        */
        scooterPanel.setSize(biciPanel.getPreferredSize());
        scooterPanel.setLocation(biciPanel.getX(),biciPanel.getY());
        patinetePanel.setLocation(biciPanel.getX(),biciPanel.getY());
        //aceptarButton.setLocation(aceptarButton.getX(),aceptarButton.getY()-(scooterPanel.getHeight()*2));
        scooterPanel.setVisible(false);
        patinetePanel.setVisible(false);
        jPanel2.setPreferredSize(new Dimension(jPanel2.getWidth(),aceptarButton.getY()+aceptarButton.getHeight()));
        setSize(getWidth(), (int) jPanel2.getPreferredSize().getHeight());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        aceptarButton = new javax.swing.JButton();
        biciButton = new javax.swing.JButton();
        scooterButton = new javax.swing.JButton();
        patineteButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        biciPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        scooterPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        patinetePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(60, 65, 66));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel2.setBackground(new java.awt.Color(60, 64, 65));

        aceptarButton.setBackground(new java.awt.Color(78, 81, 82));
        aceptarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aceptarButton.setForeground(new java.awt.Color(255, 255, 255));
        aceptarButton.setText("ACEPTAR");
        aceptarButton.setFocusable(false);
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        biciButton.setBackground(new java.awt.Color(78, 81, 82));
        biciButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        biciButton.setForeground(new java.awt.Color(255, 255, 255));
        biciButton.setText("BICICLETA");
        biciButton.setEnabled(false);
        biciButton.setFocusable(false);
        biciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biciButtonActionPerformed(evt);
            }
        });

        scooterButton.setBackground(new java.awt.Color(78, 81, 82));
        scooterButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        scooterButton.setForeground(new java.awt.Color(255, 255, 255));
        scooterButton.setText("SCOOTER");
        scooterButton.setFocusable(false);
        scooterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scooterButtonActionPerformed(evt);
            }
        });

        patineteButton.setBackground(new java.awt.Color(78, 81, 82));
        patineteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patineteButton.setForeground(new java.awt.Color(255, 255, 255));
        patineteButton.setText("PATINETE");
        patineteButton.setFocusable(false);
        patineteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patineteButtonActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(70, 74, 75));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NORMAL", "ELECTRICO" }));

        jLabel1.setBackground(new java.awt.Color(60, 64, 65));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CODIGO");

        jTextField1.setBackground(new java.awt.Color(70, 74, 75));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(60, 64, 65));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TIPO");

        biciPanel.setBackground(new java.awt.Color(60, 64, 65));
        biciPanel.setPreferredSize(new java.awt.Dimension(285, 40));

        jLabel3.setBackground(new java.awt.Color(60, 64, 65));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CANTIDAD CAMBIOS");

        jComboBox3.setBackground(new java.awt.Color(70, 74, 75));
        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        javax.swing.GroupLayout biciPanelLayout = new javax.swing.GroupLayout(biciPanel);
        biciPanel.setLayout(biciPanelLayout);
        biciPanelLayout.setHorizontalGroup(
            biciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biciPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(biciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biciPanelLayout.createSequentialGroup()
                    .addContainerGap(221, Short.MAX_VALUE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)))
        );
        biciPanelLayout.setVerticalGroup(
            biciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biciPanelLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(biciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biciPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jComboBox3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        scooterPanel.setBackground(new java.awt.Color(60, 64, 65));
        scooterPanel.setPreferredSize(new java.awt.Dimension(285, 40));

        jLabel4.setBackground(new java.awt.Color(60, 64, 65));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("COLOR");

        jTextField2.setBackground(new java.awt.Color(70, 74, 75));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout scooterPanelLayout = new javax.swing.GroupLayout(scooterPanel);
        scooterPanel.setLayout(scooterPanelLayout);
        scooterPanelLayout.setHorizontalGroup(
            scooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scooterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        scooterPanelLayout.setVerticalGroup(
            scooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scooterPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(scooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        patinetePanel.setBackground(new java.awt.Color(60, 64, 65));
        patinetePanel.setPreferredSize(new java.awt.Dimension(285, 40));

        jLabel5.setBackground(new java.awt.Color(60, 64, 65));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CANTIDAD RUEDAS");

        jComboBox2.setBackground(new java.awt.Color(70, 74, 75));
        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        javax.swing.GroupLayout patinetePanelLayout = new javax.swing.GroupLayout(patinetePanel);
        patinetePanel.setLayout(patinetePanelLayout);
        patinetePanelLayout.setHorizontalGroup(
            patinetePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patinetePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        patinetePanelLayout.setVerticalGroup(
            patinetePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patinetePanelLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(patinetePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(biciPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addComponent(scooterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(biciButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scooterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patineteButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(patinetePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(biciButton)
                    .addComponent(scooterButton)
                    .addComponent(patineteButton))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(biciPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scooterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patinetePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void biciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biciButtonActionPerformed
        //cambiar la vista al panel de bicicleta
        biciButton.setEnabled(false);
        scooterButton.setEnabled(true);
        patineteButton.setEnabled(true);
        
        biciPanel.setVisible(true);
        scooterPanel.setVisible(false);
        patinetePanel.setVisible(false);
        jPanel2.repaint();                
    }//GEN-LAST:event_biciButtonActionPerformed

    private void scooterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scooterButtonActionPerformed
        //cambiar la vista al panel de scooter
        biciButton.setEnabled(true);
        scooterButton.setEnabled(false);
        patineteButton.setEnabled(true);
        
        biciPanel.setVisible(false);
        scooterPanel.setVisible(true);
        patinetePanel.setVisible(false);
        jPanel2.repaint();                
    }//GEN-LAST:event_scooterButtonActionPerformed

    private void patineteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patineteButtonActionPerformed
        //cambiar la vista al panel de patinete
        biciButton.setEnabled(true);
        scooterButton.setEnabled(true);
        patineteButton.setEnabled(false);
        
        biciPanel.setVisible(false);
        scooterPanel.setVisible(false);
        patinetePanel.setVisible(true);
        jPanel2.repaint();                
    }//GEN-LAST:event_patineteButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        
        /*
            se crea un transporte nuevo con la informacion
            primero se revisa que el codigo sea valido
            si no lo es se da error
            en caso de serlo se intenta agregar a la lista
            de transportes, si no es posbile es debido
            a que el codgio ya esta siendo usado
            en dicho caso se informa tambien al usuario
            si no hay problemas se agrega a la lista y se actualiza
            la tabla de transportes
        */
        Transporte t = null;
        String codigo = jTextField1.getText();
        if(!Transporte.codigoValido(codigo)){
            JOptionPane.showMessageDialog(null,"CODIGO NO VALIDO");
            return;
        }
        String tipo = (String)jComboBox1.getSelectedItem();
        
        if(!biciButton.isEnabled()){
            int cambios = jComboBox3.getSelectedIndex()+1;
            t = new Bicicleta(codigo,tipo,cambios);
        }
        else if (!scooterButton.isEnabled()){
            String color = jTextField2.getText();
            t = new Scooter(codigo,tipo,color);
        }
        else if(!patineteButton.isEnabled()){
            int ruedas = jComboBox2.getSelectedIndex()+1;
            t = new Patinete(codigo,tipo,ruedas);
        }
        int result = datos.agregarTransporte(t);
        if(result == 0){
            mainWindow.updateTransporteTable();
            dispose();
        }       
        else if(result == 1){
            JOptionPane.showMessageDialog(null,"Codigo ya usado");
        }
        
    }//GEN-LAST:event_aceptarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton biciButton;
    private javax.swing.JPanel biciPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton patineteButton;
    private javax.swing.JPanel patinetePanel;
    private javax.swing.JButton scooterButton;
    private javax.swing.JPanel scooterPanel;
    // End of variables declaration//GEN-END:variables
}
