package visual;
import control.Datos;
import entidades.*;
import java.awt.Color;
import javax.swing.JOptionPane;

public class NuevoAlquilerWindow extends javax.swing.JFrame {

    /**
     * Creates new form NuevoAlquilerWindow
     */
    Datos datos;
    Cliente cliente;
    Transporte transporte;
    int distancia;
    boolean correcto = false;
    MainWindow mainWindow;
    public NuevoAlquilerWindow(Datos datos,MainWindow mainWindow) {
        
        this.mainWindow = mainWindow;
        this.datos = datos;
        initComponents();
        edadSelector.setBackground(clientePanel.getBackground());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transportePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        facturaPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        nombreLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        transporteLabel = new javax.swing.JLabel();
        montoLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        clientePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        direccionTextField = new javax.swing.JTextField();
        edadSelector = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        transportePanel.setBackground(new java.awt.Color(60, 64, 65));

        jLabel3.setBackground(new java.awt.Color(60, 64, 65));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TRANSPORTE");

        jTextField4.setBackground(new java.awt.Color(70, 74, 75));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("Codigo");
        jTextField4.setCaretColor(new java.awt.Color(255, 255, 255));

        jTextField6.setBackground(new java.awt.Color(70, 74, 75));
        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("Distancia");
        jTextField6.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField6.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField6CaretUpdate(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(78, 80, 81));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CONTINUAR");
        jButton2.setEnabled(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(60, 64, 65));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("0");

        jButton3.setBackground(new java.awt.Color(78, 80, 81));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BUSCAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transportePanelLayout = new javax.swing.GroupLayout(transportePanel);
        transportePanel.setLayout(transportePanelLayout);
        transportePanelLayout.setHorizontalGroup(
            transportePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transportePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transportePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transportePanelLayout.createSequentialGroup()
                        .addGroup(transportePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transportePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(transportePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(transportePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        transportePanelLayout.setVerticalGroup(
            transportePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transportePanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(transportePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transportePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(transportePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(transportePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(333, 333, 333)))
        );

        facturaPanel.setBackground(new java.awt.Color(60, 64, 65));

        jLabel4.setBackground(new java.awt.Color(60, 64, 65));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FACTURA");

        jButton4.setBackground(new java.awt.Color(78, 80, 81));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CONTINUAR");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        nombreLabel.setBackground(new java.awt.Color(60, 65, 65));
        nombreLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreLabel.setText("NOMBRE CLIENTE");

        idLabel.setBackground(new java.awt.Color(60, 65, 65));
        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLabel.setText("ID CLIENTE");

        transporteLabel.setBackground(new java.awt.Color(60, 65, 65));
        transporteLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        transporteLabel.setForeground(new java.awt.Color(255, 255, 255));
        transporteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transporteLabel.setText("CODIGO TRANSPORTE");

        montoLabel.setBackground(new java.awt.Color(60, 65, 65));
        montoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        montoLabel.setForeground(new java.awt.Color(255, 255, 255));
        montoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        montoLabel.setText("MONTO A PAGAR");

        javax.swing.GroupLayout facturaPanelLayout = new javax.swing.GroupLayout(facturaPanel);
        facturaPanel.setLayout(facturaPanelLayout);
        facturaPanelLayout.setHorizontalGroup(
            facturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transporteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(montoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(facturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(facturaPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        facturaPanelLayout.setVerticalGroup(
            facturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturaPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transporteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(montoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(facturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(facturaPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(319, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(60, 64, 65));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jTabbedPane1.setBackground(new java.awt.Color(60, 65, 65));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        clientePanel.setBackground(new java.awt.Color(60, 64, 65));

        jLabel1.setBackground(new java.awt.Color(60, 64, 65));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLIENTE");

        nombreTextField.setBackground(new java.awt.Color(70, 74, 75));
        nombreTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreTextField.setForeground(new java.awt.Color(255, 255, 255));
        nombreTextField.setText("Nombre");
        nombreTextField.setCaretColor(new java.awt.Color(255, 255, 255));

        idTextField.setBackground(new java.awt.Color(70, 74, 75));
        idTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idTextField.setForeground(new java.awt.Color(255, 255, 255));
        idTextField.setText("ID:");
        idTextField.setCaretColor(new java.awt.Color(255, 255, 255));

        direccionTextField.setBackground(new java.awt.Color(70, 74, 75));
        direccionTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        direccionTextField.setForeground(new java.awt.Color(255, 255, 255));
        direccionTextField.setText("Direccion");
        direccionTextField.setCaretColor(new java.awt.Color(255, 255, 255));

        edadSelector.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edadSelector.setModel(new javax.swing.SpinnerNumberModel(18, 18, 100, 1));
        edadSelector.setDoubleBuffered(true);
        edadSelector.setEditor(new javax.swing.JSpinner.NumberEditor(edadSelector, ""));
        edadSelector.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(60, 64, 65));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EDAD");
        jLabel2.setFocusable(false);

        jButton1.setBackground(new java.awt.Color(78, 80, 81));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONTINUAR");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clientePanelLayout = new javax.swing.GroupLayout(clientePanel);
        clientePanel.setLayout(clientePanelLayout);
        clientePanelLayout.setHorizontalGroup(
            clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreTextField)
                    .addComponent(idTextField)
                    .addComponent(direccionTextField)
                    .addGroup(clientePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edadSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(clientePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        clientePanelLayout.setVerticalGroup(
            clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientePanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(clientePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(333, 333, 333)))
        );

        jTabbedPane1.addTab("CLIENTE", clientePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //obtener datos del cliente
        this.cliente = new Cliente(nombreTextField.getText(),
                                   idTextField.getText(),
                                   direccionTextField.getText(),
                                   (int)edadSelector.getValue());
        //si no se ha agregado la siguiente ventana agregarla
        // y cambiar a esta
        if(jTabbedPane1.getTabCount() == 1)
            jTabbedPane1.addTab("TRANSPORTE", transportePanel);
        nombreLabel.setText(cliente.getNombre());
        idLabel.setText(cliente.getId());
        jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex()+1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //buscar transporte por el codigo seleccionado
        //poner en rojo o verde el boton si se encontró o no
        String codigo = jTextField4.getText();
        this.transporte = datos.getTransporte(codigo);
        if(this.transporte == null){
            //JOptionPane.showMessageDialog(null, "Codigo incorrecto");
            jButton3.setBackground(Color.red);           
        }        
        else jButton3.setBackground(Color.green);
        //hacer el calculo de coste
        jTextField6CaretUpdate(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField6CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField6CaretUpdate
        /*
            cada vez que escribamos en el textfield de distancia
            hacer el calculo de distancia para mostrarselo al usuario
        */
        try{
            this.distancia = Integer.parseInt(jTextField6.getText());
            jLabel6.setText("$"+this.transporte.calcularMonto(distancia));
            this.correcto = true;            
        }
        catch(Exception e){
            this.correcto = false;
        }
        jButton2.setEnabled(correcto);
    }//GEN-LAST:event_jTextField6CaretUpdate

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*
            una vez seleccionado el transporte y la distancia
            agregar la informacio al panel final de factura
            y mostrar al usuario
            si no se ha agregado agregarlo
        */
        nombreLabel.setText(cliente.getNombre());
        idLabel.setText(cliente.getId());
        transporteLabel.setText(this.transporte.getCodigo());
        montoLabel.setText("$"+this.transporte.calcularMonto(distancia));
        if(jTabbedPane1.getTabCount() == 2)
            jTabbedPane1.addTab("FACTURA", facturaPanel);        
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //al aceptar la factura crearla y agregarla 
        Factura factura = new Factura(System.currentTimeMillis()+"", this.transporte, cliente, distancia, this.transporte.calcularMonto(distancia),System.currentTimeMillis());
        datos.agregarFactura(factura);
        //actualizar la tabla
        mainWindow.updateAlquilerTable();
        //cerrar la ventana
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clientePanel;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JSpinner edadSelector;
    private javax.swing.JPanel facturaPanel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel montoLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel transporteLabel;
    private javax.swing.JPanel transportePanel;
    // End of variables declaration//GEN-END:variables
}
