/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import Modelo.ClaseRecetas;
import java.util.ArrayList;
import Modelo.ClasePacienteConsulta;
import Modelo.ClasePacienteInternado;
import Modelo.ClaseReporteQuirurjico;
import Modelo.ClaseReporteInternado;
import Modelo.ClaseReporteConsulta;
/**
 *
 * @author sinai
 */
public class Receta extends javax.swing.JFrame {
    String via;
    String medicamento;
    String dosis;
    int frecuencia;
    /**
     * Creates new form Receta
     */
    
    FondoPanel fondo = new FondoPanel();//Visualizar fondo de panel
    
    public Receta() {
        this.setContentPane(fondo);//Visualizar fondo de panel
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSeguir2 = new javax.swing.JButton();
        PanelAmbulatorio3 = new FondoPanel();
        lbTituloVReceta = new javax.swing.JLabel();
        lbMedicamentosRecetaAmb = new javax.swing.JLabel();
        lbDosisRecetaAmb = new javax.swing.JLabel();
        lbFrecuenciaRecetaAmb = new javax.swing.JLabel();
        lbViaRecetaAmb = new javax.swing.JLabel();
        btnNuevoMedicamentoAmb = new javax.swing.JButton();
        btnFinalizarRecetaAmb = new javax.swing.JButton();
        txtMedicamento = new javax.swing.JTextField();
        txtDosis = new javax.swing.JTextField();
        txtFrecuencia = new javax.swing.JTextField();
        txtVia = new javax.swing.JTextField();

        btnSeguir2.setBackground(new java.awt.Color(0, 153, 153));
        btnSeguir2.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnSeguir2.setText("Nuevo medicamento");
        btnSeguir2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloVReceta.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        lbTituloVReceta.setText("Receta.");

        lbMedicamentosRecetaAmb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMedicamentosRecetaAmb.setText("Medicamento:");

        lbDosisRecetaAmb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbDosisRecetaAmb.setText(" Dosis:");

        lbFrecuenciaRecetaAmb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbFrecuenciaRecetaAmb.setText("Frecuencia:");

        lbViaRecetaAmb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbViaRecetaAmb.setText("Vía:");

        btnNuevoMedicamentoAmb.setBackground(new java.awt.Color(0, 153, 153));
        btnNuevoMedicamentoAmb.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnNuevoMedicamentoAmb.setText("Guardar Receta");
        btnNuevoMedicamentoAmb.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnNuevoMedicamentoAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoMedicamentoAmbActionPerformed(evt);
            }
        });

        btnFinalizarRecetaAmb.setBackground(new java.awt.Color(0, 153, 153));
        btnFinalizarRecetaAmb.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnFinalizarRecetaAmb.setText("Omitir");
        btnFinalizarRecetaAmb.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnFinalizarRecetaAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarRecetaAmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAmbulatorio3Layout = new javax.swing.GroupLayout(PanelAmbulatorio3);
        PanelAmbulatorio3.setLayout(PanelAmbulatorio3Layout);
        PanelAmbulatorio3Layout.setHorizontalGroup(
            PanelAmbulatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAmbulatorio3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbTituloVReceta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAmbulatorio3Layout.createSequentialGroup()
                .addGroup(PanelAmbulatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelAmbulatorio3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnNuevoMedicamentoAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizarRecetaAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelAmbulatorio3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PanelAmbulatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMedicamentosRecetaAmb)
                            .addComponent(lbDosisRecetaAmb)
                            .addComponent(lbFrecuenciaRecetaAmb)
                            .addComponent(lbViaRecetaAmb))
                        .addGap(35, 35, 35)
                        .addGroup(PanelAmbulatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAmbulatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelAmbulatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtFrecuencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtVia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addGap(56, 56, 56))
        );
        PanelAmbulatorio3Layout.setVerticalGroup(
            PanelAmbulatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAmbulatorio3Layout.createSequentialGroup()
                .addGroup(PanelAmbulatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAmbulatorio3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbTituloVReceta))
                    .addGroup(PanelAmbulatorio3Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(PanelAmbulatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMedicamentosRecetaAmb)
                            .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(PanelAmbulatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAmbulatorio3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbDosisRecetaAmb))
                    .addGroup(PanelAmbulatorio3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(PanelAmbulatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFrecuenciaRecetaAmb)
                    .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PanelAmbulatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbViaRecetaAmb)
                    .addComponent(txtVia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(PanelAmbulatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizarRecetaAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoMedicamentoAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAmbulatorio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAmbulatorio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarRecetaAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarRecetaAmbActionPerformed
  
    JOptionPane.showMessageDialog(rootPane, "Paciente registrado con éxito!");
    this.dispose();
    new Ventana1().setVisible(true);
        
    }//GEN-LAST:event_btnFinalizarRecetaAmbActionPerformed

    private void btnNuevoMedicamentoAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoMedicamentoAmbActionPerformed
        // TODO add your handling code here:
        try{
            //Atributos de la receta:
            this.medicamento = this.txtMedicamento.getText();
            this.via = this.txtVia.getText();
            this.dosis = this.txtDosis.getText();
            this.frecuencia = Integer.parseInt(this.txtFrecuencia.getText());
            
            //Creación de la clase Receta:
            ClaseRecetas receta1 = new ClaseRecetas(this.medicamento, this.dosis, this.frecuencia, this.via);
            
            //la recetase enviará al objeto de reporte consulta si el paciente es de tipo ambulatorio
            if (Ventana2.validador == true){
                VentanaReporteAmbulatorio.reporteConsulta.getListaRecetas().add(receta1);
            }
            //La receta se enviará al reporte de de internado o a quirurgico dependiendo de cual se haya creado
            else{
                if(Ventana3.validador == true){
                    VentanaReporteInterno.reporteInternado.getListaRecetas().add(receta1);
                }
                else{
                    VentanaReporteQuirurgico2.reporteQuirurjico.getListaRecetas().add(receta1);
                }
            }
            
            JOptionPane.showMessageDialog(rootPane, "Receta registrada\nIngrese una nueva receta o presione omitr para salir");
        }
        catch(ClassCastException e1){
            JOptionPane.showMessageDialog(rootPane, "Tipo de dato incorrecto");
        }
        catch(NumberFormatException e2){
            JOptionPane.showMessageDialog(rootPane, "Tipo de dato incorrecto");
        }
        
    }//GEN-LAST:event_btnNuevoMedicamentoAmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAmbulatorio3;
    private javax.swing.JButton btnFinalizarRecetaAmb;
    private javax.swing.JButton btnNuevoMedicamentoAmb;
    private javax.swing.JButton btnSeguir2;
    private javax.swing.JLabel lbDosisRecetaAmb;
    private javax.swing.JLabel lbFrecuenciaRecetaAmb;
    private javax.swing.JLabel lbMedicamentosRecetaAmb;
    private javax.swing.JLabel lbTituloVReceta;
    private javax.swing.JLabel lbViaRecetaAmb;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtFrecuencia;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtVia;
    // End of variables declaration//GEN-END:variables

    //Visualizar el fondo
    class FondoPanel extends JPanel { //Visualizar fondo en la ventana
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Imagenes/5.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
