/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Modelo.ClasePacienteConsulta;
import Modelo.ClaseReportes;
import java.util.ArrayList;

/**
 *
 * @author sinai
 */
public class VentanaRegistroAmbulatorio extends javax.swing.JFrame {
    static ClasePacienteConsulta pacienteConsulta;
    static String nombre;
    static String medico;
    static int edad;
    static String genero;
    static String patologias;
    static int identificador;
    

    /**
     * Creates new form VentanaRegistro
     */
    
    FondoPanel fondo = new FondoPanel();//Visualizar fondo de panel
    
    public VentanaRegistroAmbulatorio() {
        this.setContentPane(fondo);//Visualizar fondo de panel
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAmbulatorio1 = new FondoPanel();
        lbTituloVRegistro = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbEdad = new javax.swing.JLabel();
        lbGenero = new javax.swing.JLabel();
        lbMedico = new javax.swing.JLabel();
        lbPatologia = new javax.swing.JLabel();
        lbIdentificador = new javax.swing.JLabel();
        btnSeguir1 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtMedico = new javax.swing.JTextField();
        txtPatologia = new javax.swing.JTextField();
        txtIdentificador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloVRegistro.setFont(new java.awt.Font("Arial Narrow", 1, 34)); // NOI18N
        lbTituloVRegistro.setText("Registrar paciente Ambulatorio:");

        lbNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNombre.setText("Nombre:");

        lbEdad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEdad.setText("Edad:");

        lbGenero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGenero.setText("Género:");

        lbMedico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMedico.setText("Médico en turno:");

        lbPatologia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPatologia.setText("Patología: ");

        lbIdentificador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbIdentificador.setText("ID: ");

        btnSeguir1.setBackground(new java.awt.Color(0, 153, 153));
        btnSeguir1.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnSeguir1.setText("Siguiente");
        btnSeguir1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnSeguir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguir1ActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Malayalam MN", 1, 20)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicoActionPerformed(evt);
            }
        });

        txtIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAmbulatorio1Layout = new javax.swing.GroupLayout(PanelAmbulatorio1);
        PanelAmbulatorio1.setLayout(PanelAmbulatorio1Layout);
        PanelAmbulatorio1Layout.setHorizontalGroup(
            PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAmbulatorio1Layout.createSequentialGroup()
                .addGroup(PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelAmbulatorio1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTituloVRegistro))
                    .addGroup(PanelAmbulatorio1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbGenero)
                            .addComponent(lbNombre))
                        .addGap(57, 57, 57)
                        .addGroup(PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelAmbulatorio1Layout.createSequentialGroup()
                                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(lbEdad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelAmbulatorio1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnRegresar)
                        .addGap(182, 182, 182)
                        .addComponent(btnSeguir1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAmbulatorio1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMedico)
                            .addComponent(lbPatologia)
                            .addComponent(lbIdentificador))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPatologia)
                            .addGroup(PanelAmbulatorio1Layout.createSequentialGroup()
                                .addGroup(PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        PanelAmbulatorio1Layout.setVerticalGroup(
            PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAmbulatorio1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbTituloVRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAmbulatorio1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbNombre)
                        .addGap(18, 18, 18)
                        .addGroup(PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEdad)
                            .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGenero)))
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMedico)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPatologia)
                    .addComponent(txtPatologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdentificador)
                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(PanelAmbulatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeguir1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAmbulatorio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAmbulatorio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeguir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguir1ActionPerformed
        // TODO add your handling code here:
        try{
            //Atributos del paciente ambulatorio
            this.nombre = this.txtNombre.getText();
            this.edad = Integer.parseInt(this.txtEdad.getText());
            this.genero = this.txtGenero.getText();
            this.medico = this.txtMedico.getText();
            
            if(this.txtPatologia.getText().isEmpty()){
                this.txtPatologia.setText("N/A");
            }
            
            this.patologias = this.txtPatologia.getText();
            this.identificador = Integer.parseInt(this.txtIdentificador.getText());
            
            //Crear lista de reportes para la creación del paciente ambulatorio:
            ArrayList<ClaseReportes> listaReportes = new ArrayList();
           
            //Crear instancia de paciente ambulatorio:
            this.pacienteConsulta = new ClasePacienteConsulta(this.nombre, this.edad, this.genero, this.medico, this.patologias, this.identificador, listaReportes);
            
            //Añadir el paciente creado a la lista de pacientes de consulta
            EjecutarProgramaPacientes.listaPacienteConsulta.add(this.pacienteConsulta);
            
            //Cerrar ventana ya abrir la siguiente:
            this.dispose();
            new VentanaReporteAmbulatorio().setVisible(true);
        }
        catch(ClassCastException e1){
            JOptionPane.showMessageDialog(rootPane, "Tipo de dato incorrecto");
        }
        catch(NumberFormatException e2){
            JOptionPane.showMessageDialog(rootPane, "Tipo de dato incorrecto");
        }
       
    }//GEN-LAST:event_btnSeguir1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        //Declarar y establecer los atributos del paciente interno:
        
        this.dispose();
        new Ventana2().setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificadorActionPerformed

    private void txtMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAmbulatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAmbulatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAmbulatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAmbulatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroAmbulatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAmbulatorio1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSeguir1;
    private javax.swing.JLabel lbEdad;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbIdentificador;
    private javax.swing.JLabel lbMedico;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPatologia;
    private javax.swing.JLabel lbTituloVRegistro;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPatologia;
    // End of variables declaration//GEN-END:variables

    //Visualizar el fondo
    class FondoPanel extends JPanel { //Visualizar fondo en la ventana
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Imagenes/4.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
