/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author sinai
 */
public class Ventana2 extends javax.swing.JFrame {
    
    //validador servirá para saber el tipo de paciente que se quiere registrar;
    static boolean validador;
    /**
     * Creates new form Ventana2
     */
    FondoPanel fondo = new FondoPanel();//Visualizar fondo de panel
    
    public Ventana2() {
        this.setContentPane(fondo);//Visualizar fondo de panel
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vtnOpcionRegistro = new FondoPanel();
        lbTituloV2 = new javax.swing.JLabel();
        btnAmbulatorio = new javax.swing.JButton();
        btnHospitalizado = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloV2.setFont(new java.awt.Font("Arial Narrow", 1, 34)); // NOI18N
        lbTituloV2.setText("Registrar Paciente:");

        btnAmbulatorio.setBackground(new java.awt.Color(0, 153, 153));
        btnAmbulatorio.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        btnAmbulatorio.setText("AMBULATORIO");
        btnAmbulatorio.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnAmbulatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmbulatorioActionPerformed(evt);
            }
        });

        btnHospitalizado.setBackground(new java.awt.Color(0, 153, 153));
        btnHospitalizado.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        btnHospitalizado.setText("HOSPITALIZADO");
        btnHospitalizado.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnHospitalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalizadoActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 51, 51));
        btnRegresar.setFont(new java.awt.Font("Malayalam MN", 1, 20)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vtnOpcionRegistroLayout = new javax.swing.GroupLayout(vtnOpcionRegistro);
        vtnOpcionRegistro.setLayout(vtnOpcionRegistroLayout);
        vtnOpcionRegistroLayout.setHorizontalGroup(
            vtnOpcionRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vtnOpcionRegistroLayout.createSequentialGroup()
                .addGroup(vtnOpcionRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vtnOpcionRegistroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTituloV2))
                    .addGroup(vtnOpcionRegistroLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnAmbulatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnHospitalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vtnOpcionRegistroLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnRegresar)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        vtnOpcionRegistroLayout.setVerticalGroup(
            vtnOpcionRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vtnOpcionRegistroLayout.createSequentialGroup()
                .addComponent(lbTituloV2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(vtnOpcionRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAmbulatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHospitalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(btnRegresar)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vtnOpcionRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vtnOpcionRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAmbulatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbulatorioActionPerformed
        // TODO add your handling code here:
        validador = true;
        this.dispose();
        new VentanaRegistroAmbulatorio().setVisible(true);
    }//GEN-LAST:event_btnAmbulatorioActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Ventana1().setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnHospitalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalizadoActionPerformed
        // TODO add your handling code here:
        validador = false;
        this.dispose();
        new VentanaRegistroInterno().setVisible(true);
    }//GEN-LAST:event_btnHospitalizadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmbulatorio;
    private javax.swing.JButton btnHospitalizado;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lbTituloV2;
    private javax.swing.JPanel vtnOpcionRegistro;
    // End of variables declaration//GEN-END:variables

    //Visualizar el fondo
    class FondoPanel extends JPanel { //Visualizar fondo en la ventana
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Imagenes/3.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
