/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import Modelo.ClasePacienteInternado;
import Modelo.ClaseReportes;
import Modelo.ClaseActividades;
import java.util.ArrayList;
/**
 *
 * @author sinai
 */
public class VentanaRegistroInterno extends javax.swing.JFrame {
    static ClasePacienteInternado pacienteHospitalizado;
    static ArrayList<ClaseActividades> itineriario = new ArrayList();
    static String nombre;
    static int edad;
    static String genero;
    static String medico;
    static String patologias;
    static int identificador;
    
    /**
     * Creates new form VentanaRegistro
     */
    
    FondoPanel fondo = new FondoPanel();//Visualizar fondo de panel
    
    public VentanaRegistroInterno() {
        this.setContentPane(fondo);//Visualizar fondo de panel
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInterno1 = new FondoPanel();
        lbTituloVRegistroInterno = new javax.swing.JLabel();
        lbNombreInterno = new javax.swing.JLabel();
        lbEdadInterno = new javax.swing.JLabel();
        lbGeneroInterno = new javax.swing.JLabel();
        lbMedicoInterno = new javax.swing.JLabel();
        lbPatologiaInterno = new javax.swing.JLabel();
        lbIdentificadorInterno = new javax.swing.JLabel();
        btnSeguirInterno1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtNombreInterno = new javax.swing.JTextField();
        txtGeneroInterno = new javax.swing.JTextField();
        txtEdadInterno = new javax.swing.JTextField();
        txtMedico = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPatologiaInterno = new javax.swing.JTextField();
        txtIdentificadorInterno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloVRegistroInterno.setFont(new java.awt.Font("Arial Narrow", 1, 34)); // NOI18N
        lbTituloVRegistroInterno.setText("Registro paciente Interno:");

        lbNombreInterno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNombreInterno.setText("Nombre:");

        lbEdadInterno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEdadInterno.setText("Edad:");

        lbGeneroInterno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGeneroInterno.setText("Género:");

        lbMedicoInterno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMedicoInterno.setText("Médico en turno:");

        lbPatologiaInterno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPatologiaInterno.setText("Patología: ");

        lbIdentificadorInterno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbIdentificadorInterno.setText("ID: ");

        btnSeguirInterno1.setBackground(new java.awt.Color(0, 153, 153));
        btnSeguirInterno1.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnSeguirInterno1.setText("Siguiente");
        btnSeguirInterno1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnSeguirInterno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguirInterno1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Malayalam MN", 1, 20)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtIdentificadorInterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificadorInternoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInterno1Layout = new javax.swing.GroupLayout(PanelInterno1);
        PanelInterno1.setLayout(PanelInterno1Layout);
        PanelInterno1Layout.setHorizontalGroup(
            PanelInterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInterno1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTituloVRegistroInterno)
                    .addComponent(lbIdentificadorInterno)
                    .addGroup(PanelInterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelInterno1Layout.createSequentialGroup()
                            .addGroup(PanelInterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbNombreInterno)
                                .addComponent(lbGeneroInterno))
                            .addGap(18, 18, 18)
                            .addGroup(PanelInterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelInterno1Layout.createSequentialGroup()
                                    .addComponent(txtGeneroInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(lbEdadInterno)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtEdadInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtNombreInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelInterno1Layout.createSequentialGroup()
                            .addComponent(lbMedicoInterno)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtMedico))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelInterno1Layout.createSequentialGroup()
                            .addComponent(lbPatologiaInterno)
                            .addGap(34, 34, 34)
                            .addGroup(PanelInterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelInterno1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtPatologiaInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIdentificadorInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelInterno1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton1)
                        .addGap(176, 176, 176)
                        .addComponent(btnSeguirInterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        PanelInterno1Layout.setVerticalGroup(
            PanelInterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInterno1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloVRegistroInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelInterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreInterno)
                    .addComponent(txtNombreInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelInterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGeneroInterno)
                    .addComponent(txtGeneroInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEdadInterno)
                    .addComponent(txtEdadInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelInterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMedicoInterno)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelInterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPatologiaInterno)
                    .addComponent(jLabel1)
                    .addComponent(txtPatologiaInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelInterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdentificadorInterno)
                    .addComponent(txtIdentificadorInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(PanelInterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeguirInterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInterno1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInterno1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Ventana2().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSeguirInterno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguirInterno1ActionPerformed
        // TODO add your handling code here:
        
        //Declarar y establecer los atributos del paciente interno:
        try{
            //Atributos del paciente de tipo hospitalizado(interno)
            this.nombre = this.txtNombreInterno.getText();
            this.edad = Integer.parseInt(this.txtEdadInterno.getText());
            this.genero = this.txtGeneroInterno.getText();
            this.medico = this.txtMedico.getText();
            if(this.txtPatologiaInterno.getText().isEmpty()){
                this.txtPatologiaInterno.setText("N/A");
            }
            this.patologias = this.txtPatologiaInterno.getText();
            this.identificador = Integer.parseInt(this.txtIdentificadorInterno.getText());
            
            
            //Creación de una lista de reportes para crear al paciente hospitalizado
            ArrayList<ClaseReportes> listaReportesInternados = new ArrayList();
            
            //Crear objeto Paciene internado:
            this.pacienteHospitalizado =  new ClasePacienteInternado(this.itineriario , listaReportesInternados, this.nombre, this.edad, this.genero, this.medico, this.patologias, this.identificador);
            
            //Añadir el paciente creado a la lista de pacientes de consulta:
            EjecutarProgramaPacientes.listaPacienteInternado.add(pacienteHospitalizado);
            
            //Cerrar ventana y abrir la siguiente
            this.dispose();
            new Ventana3().setVisible(true);
        }
        catch(ClassCastException e1){
            JOptionPane.showMessageDialog(rootPane, "Tipo de dato incorrecto");
        }
        catch(NumberFormatException e2){
            JOptionPane.showMessageDialog(rootPane, "Tipo de dato incorrecto");
        }
        
        
    }//GEN-LAST:event_btnSeguirInterno1ActionPerformed

    private void txtIdentificadorInternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificadorInternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificadorInternoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroInterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroInterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroInterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroInterno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroInterno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInterno1;
    private javax.swing.JButton btnSeguirInterno1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbEdadInterno;
    private javax.swing.JLabel lbGeneroInterno;
    private javax.swing.JLabel lbIdentificadorInterno;
    private javax.swing.JLabel lbMedicoInterno;
    private javax.swing.JLabel lbNombreInterno;
    private javax.swing.JLabel lbPatologiaInterno;
    private javax.swing.JLabel lbTituloVRegistroInterno;
    private javax.swing.JTextField txtEdadInterno;
    private javax.swing.JTextField txtGeneroInterno;
    private javax.swing.JTextField txtIdentificadorInterno;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtNombreInterno;
    private javax.swing.JTextField txtPatologiaInterno;
    // End of variables declaration//GEN-END:variables

    //Visualizar el fondo
    class FondoPanel extends JPanel { //Visualizar fondo en la ventana
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Imagenes/4.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
