package ventana;

import control.*;
import java.awt.Color;
import visual.*;

public class PartidaPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    
    private final ControlJuego control = new ControlJuego();
    private final ControlPieza controlPieza = new ControlPieza();    
    private final Tablero tablero;
    private final Generador generador;
    private final Marcador puntaje;
    private final Marcador nivel;
    private final Marcador lineas;
    ControlVentana controlVentana;
    
    public PartidaPanel(ControlVentana controlVentana) {        
        this.controlVentana = controlVentana;
        initComponents();
        setSize(VARIABLESGLOBALES.WINDOWS_WIDTH,VARIABLESGLOBALES.WINDOWS_HEIGHT);                        
        
        tablero = new Tablero(20,10);
        tablero.setSize(tableroPanel.getSize());

        tablero.setBlockSize((int) (tableroPanel.getPreferredSize().getWidth()/tablero.getColumnas()));                        
        tableroPanel.add(tablero);

        generador = new Generador();
        generador.setSize(generadorPanel.getSize());
        generadorPanel.add(generador);

        puntaje = new Marcador();
        puntaje.setSize(puntajePanel.getSize());
        puntajePanel.add(puntaje);


        nivel = new Marcador();
        nivel.setSize(nivelPanel.getSize());
        nivelPanel.add(nivel);

        lineas = new Marcador();
        lineas.setSize(lineasPanel.getSize());
        lineasPanel.add(lineas);

        control.establecerDeteccionTeclado(PartidaPanel.this);        
        tablero.repaint();
        puntaje.setDato(tablero.getPuntaje());
        nivel.setDato(tablero.getNivel());
        lineas.setDato(tablero.getLineasCompletadas());
    }

    public void jugar(){
        //se resetea el tablero y todas las variables globales
        tablero.reset();
        VARIABLESGLOBALES.PAUSA = false;        
        VARIABLESGLOBALES.GAME_OVER = false;       
        VARIABLESGLOBALES.BACK_TO_MENU = false;
        control.gameLoop(generador, tablero, controlPieza, nivel, puntaje, 
                         lineas,controlVentana,controlVentana.getControlPuntaje().getPuntajes(),
                         lugarLabel,siguientePuntajeLabel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableroPanel = new javax.swing.JPanel();
        generadorPanel = new javax.swing.JPanel();
        puntajePanel = new javax.swing.JPanel();
        nivelPanel = new javax.swing.JPanel();
        lineasPanel = new javax.swing.JPanel();
        siguientePuntajeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lugarLabel = new javax.swing.JLabel();
        FondoLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(420, 600));
        setLayout(null);

        tableroPanel.setBackground(new java.awt.Color(0, 0, 255));
        tableroPanel.setFocusable(false);
        tableroPanel.setPreferredSize(new java.awt.Dimension(300, 600));
        tableroPanel.setRequestFocusEnabled(false);
        tableroPanel.setLayout(new javax.swing.BoxLayout(tableroPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(tableroPanel);
        tableroPanel.setBounds(0, 0, 300, 600);

        generadorPanel.setBackground(new java.awt.Color(204, 255, 204));
        generadorPanel.setFocusable(false);
        generadorPanel.setPreferredSize(new java.awt.Dimension(130, 130));
        generadorPanel.setLayout(new javax.swing.OverlayLayout(generadorPanel));
        add(generadorPanel);
        generadorPanel.setBounds(320, 70, 130, 120);

        puntajePanel.setBackground(new java.awt.Color(255, 0, 102));
        puntajePanel.setFocusable(false);
        puntajePanel.setLayout(new java.awt.BorderLayout());
        add(puntajePanel);
        puntajePanel.setBounds(320, 250, 130, 80);

        nivelPanel.setBackground(new java.awt.Color(0, 255, 51));
        nivelPanel.setFocusable(false);
        nivelPanel.setLayout(new java.awt.BorderLayout());
        add(nivelPanel);
        nivelPanel.setBounds(320, 390, 130, 70);

        lineasPanel.setBackground(new java.awt.Color(153, 255, 153));
        lineasPanel.setFocusable(false);
        lineasPanel.setLayout(new java.awt.BorderLayout());
        add(lineasPanel);
        lineasPanel.setBounds(320, 520, 130, 70);

        siguientePuntajeLabel.setBackground(new java.awt.Color(60, 63, 64));
        siguientePuntajeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        siguientePuntajeLabel.setForeground(new java.awt.Color(255, 255, 255));
        siguientePuntajeLabel.setText("SIGUIENTE");
        siguientePuntajeLabel.setFocusable(false);
        siguientePuntajeLabel.setOpaque(true);
        add(siguientePuntajeLabel);
        siguientePuntajeLabel.setBounds(380, 20, 80, 30);

        jLabel1.setBackground(Color.darkGray);
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LINEAS");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        add(jLabel1);
        jLabel1.setBounds(320, 480, 130, 40);

        jLabel2.setBackground(Color.darkGray);
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PUNTAJE");
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        add(jLabel2);
        jLabel2.setBounds(320, 210, 130, 40);

        jLabel3.setBackground(Color.darkGray);
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NIVEL");
        jLabel3.setFocusable(false);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        add(jLabel3);
        jLabel3.setBounds(320, 350, 130, 40);

        lugarLabel.setBackground(new java.awt.Color(60, 63, 64));
        lugarLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lugarLabel.setForeground(new java.awt.Color(255, 255, 255));
        lugarLabel.setText("LUGAR");
        lugarLabel.setFocusable(false);
        lugarLabel.setOpaque(true);
        add(lugarLabel);
        lugarLabel.setBounds(310, 20, 70, 30);

        FondoLabel.setBackground(new java.awt.Color(60, 63, 63));
        FondoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoTetris.png"))); // NOI18N
        FondoLabel.setText("jLabel4");
        FondoLabel.setFocusable(false);
        FondoLabel.setOpaque(true);
        add(FondoLabel);
        FondoLabel.setBounds(0, -4, 460, 610);
    }// </editor-fold>//GEN-END:initComponents

    public ControlPieza getControlPieza() {
        return controlPieza;
    }

    public Tablero getTablero() {
        return tablero;
    }

    public Generador getGenerador() {
        return generador;
    }

    public Marcador getPuntaje() {
        return puntaje;
    }

    public Marcador getNivel() {
        return nivel;
    }

    public Marcador getLineas() {
        return lineas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoLabel;
    private javax.swing.JPanel generadorPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel lineasPanel;
    private javax.swing.JLabel lugarLabel;
    private javax.swing.JPanel nivelPanel;
    private javax.swing.JPanel puntajePanel;
    private javax.swing.JLabel siguientePuntajeLabel;
    private javax.swing.JPanel tableroPanel;
    // End of variables declaration//GEN-END:variables
}
