package paintjcv;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;

public class InterfazPrincipal extends javax.swing.JFrame {

    private Dibujar canvas1;
    private GuardarAbrir guardar_abrir;

   
    public InterfazPrincipal() {
        super("MiniPaint");
        guardar_abrir = new GuardarAbrir();
        initComponents();

        this.setSize(655, 525);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);

        implementar_canvas();
    }

    private void implementar_canvas() {
        canvas1 = new Dibujar();
        canvas1.setBounds(20, 20, 600, 420);
        canvas1.addMouseMotionListener(new java.awt.event.MouseMotionListener() {
            @Override
            public void mouseDragged(MouseEvent me) {
                canvas1.mouseDragged(me);
            }

            @Override
            public void mouseMoved(MouseEvent me) {
            }
        });

        canvas1.addMouseListener(new java.awt.event.MouseListener() {
            @Override
            public void mouseClicked(MouseEvent me) {
            }

            @Override
            public void mousePressed(MouseEvent me) {
                canvas1.mousePressed(me);
            }

            @Override
            public void mouseReleased(MouseEvent me) {
                canvas1.mouseReleased(me);
            }

            @Override
            public void mouseEntered(MouseEvent me) {
            }

            @Override
            public void mouseExited(MouseEvent me) {
            }
        });
        this.add(canvas1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        ButtonCuadrado = new javax.swing.JButton();
        ButtonTriangulo = new javax.swing.JButton();
        ButtonCirculo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonPuntos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ButtonLineas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        MenuItemGuardar = new javax.swing.JMenuItem();
        MenuItemAbrir = new javax.swing.JMenuItem();
        MenuItemSalir = new javax.swing.JMenuItem();
        MenuEditar = new javax.swing.JMenu();
        MenuItemLimpiar = new javax.swing.JMenuItem();
        MenuItemSeleccionarColorLinea = new javax.swing.JMenuItem();
        MenuItemGrosorLinea = new javax.swing.JMenuItem();
        MenuItemSeleccionarColorFondo = new javax.swing.JMenuItem();
        MenuHerramientas = new javax.swing.JMenu();
        MenuItemBorrar = new javax.swing.JMenuItem();

        jMenuItem1.setText("Herramientas");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ButtonCuadrado.setBackground(new java.awt.Color(0, 0, 0));
        ButtonCuadrado.setIcon(new javax.swing.ImageIcon("E:\\ESCUELA\\PaintJCV\\img\\rectangulo - 32x32.png")); // NOI18N
        ButtonCuadrado.setBorder(null);
        ButtonCuadrado.setBorderPainted(false);
        ButtonCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCuadradoActionPerformed(evt);
            }
        });

        ButtonTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintjcv/triangulo - copia.png"))); // NOI18N
        ButtonTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTrianguloActionPerformed(evt);
            }
        });

        ButtonCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintjcv/circulo - copia.png"))); // NOI18N
        ButtonCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCirculoActionPerformed(evt);
            }
        });

        jLabel2.setText("Circulo");

        jLabel3.setText("Triangulo");

        ButtonPuntos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintjcv/puntos.32x32.png"))); // NOI18N
        ButtonPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPuntosActionPerformed(evt);
            }
        });

        jLabel4.setText("Puntos");

        ButtonLineas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintjcv/lineas.32x32.png"))); // NOI18N
        ButtonLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLineasActionPerformed(evt);
            }
        });

        jLabel5.setText("Lineas");

        jLabel1.setText("Cuadrado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(ButtonCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ButtonCuadrado)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonTriangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(ButtonLineas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonLineas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        MenuArchivo.setText("Archivo");

        MenuItemGuardar.setText("Guardar");
        MenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemGuardarActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuItemGuardar);

        MenuItemAbrir.setText("Abrir");
        MenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAbrirActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuItemAbrir);

        MenuItemSalir.setText("Salir");
        MenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSalirActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuItemSalir);

        BarraMenu.add(MenuArchivo);

        MenuEditar.setText("Editar");

        MenuItemLimpiar.setText("Limpiar");
        MenuItemLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLimpiarActionPerformed(evt);
            }
        });
        MenuEditar.add(MenuItemLimpiar);

        MenuItemSeleccionarColorLinea.setText("Seleccionar Color Linea");
        MenuItemSeleccionarColorLinea.setToolTipText("");
        MenuItemSeleccionarColorLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSeleccionarColorLineaActionPerformed(evt);
            }
        });
        MenuEditar.add(MenuItemSeleccionarColorLinea);

        MenuItemGrosorLinea.setText("Grosor de Linea");
        MenuItemGrosorLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemGrosorLineaActionPerformed(evt);
            }
        });
        MenuEditar.add(MenuItemGrosorLinea);

        MenuItemSeleccionarColorFondo.setText("Seleccionar Color Fondo");
        MenuItemSeleccionarColorFondo.setToolTipText("");
        MenuItemSeleccionarColorFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSeleccionarColorFondoActionPerformed(evt);
            }
        });
        MenuEditar.add(MenuItemSeleccionarColorFondo);

        BarraMenu.add(MenuEditar);

        MenuHerramientas.setText("Herramientas");

        MenuItemBorrar.setText("Borrar");
        MenuItemBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemBorrarActionPerformed(evt);
            }
        });
        MenuHerramientas.add(MenuItemBorrar);

        BarraMenu.add(MenuHerramientas);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 544, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuItemSalirActionPerformed

    private void MenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemGuardarActionPerformed

        guardar_abrir.guardar(canvas1, canvas1.shapes);

    }//GEN-LAST:event_MenuItemGuardarActionPerformed

    private void MenuItemBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemBorrarActionPerformed
        canvas1.opcion = 1;
        canvas1.color = Color.WHITE;
    }//GEN-LAST:event_MenuItemBorrarActionPerformed

    private void MenuItemSeleccionarColorLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSeleccionarColorLineaActionPerformed
        new InterfazSeleccionarColor(canvas1);
    }//GEN-LAST:event_MenuItemSeleccionarColorLineaActionPerformed

    private void MenuItemGrosorLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemGrosorLineaActionPerformed
        new InterfazGrosorLinea(canvas1);
    }//GEN-LAST:event_MenuItemGrosorLineaActionPerformed

    private void MenuItemLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLimpiarActionPerformed
        canvas1.shapes.clear();
        canvas1.repaint();
    }//GEN-LAST:event_MenuItemLimpiarActionPerformed

    private void MenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAbrirActionPerformed
        ArrayList<AtributosFormas> formas_resultado = guardar_abrir.abrir();

        if (formas_resultado != null) {
            canvas1.shapes.clear();
            canvas1.shapes = formas_resultado;
            canvas1.repaint();
        }
    }//GEN-LAST:event_MenuItemAbrirActionPerformed

    private void ButtonCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCuadradoActionPerformed
        canvas1.opcion = 4;
        canvas1.color = Color.black;
        canvas1.colorFondo = Color.WHITE;
    }//GEN-LAST:event_ButtonCuadradoActionPerformed

    private void ButtonTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTrianguloActionPerformed
        canvas1.opcion = 6;
        canvas1.color = Color.black;
        canvas1.colorFondo = Color.WHITE;
    }//GEN-LAST:event_ButtonTrianguloActionPerformed

    private void MenuItemSeleccionarColorFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSeleccionarColorFondoActionPerformed
        new InterfazSeleccionarColorFondo(canvas1);
    }//GEN-LAST:event_MenuItemSeleccionarColorFondoActionPerformed

    private void ButtonCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCirculoActionPerformed
        canvas1.opcion = 5;
        canvas1.color = Color.black;
        canvas1.colorFondo = Color.WHITE;
    }//GEN-LAST:event_ButtonCirculoActionPerformed

    private void ButtonPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPuntosActionPerformed
        canvas1.opcion = 2;
        canvas1.color = Color.black;
    }//GEN-LAST:event_ButtonPuntosActionPerformed

    private void ButtonLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLineasActionPerformed
        canvas1.opcion = 3;
        canvas1.color = Color.black;
    }//GEN-LAST:event_ButtonLineasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JButton ButtonCirculo;
    private javax.swing.JButton ButtonCuadrado;
    private javax.swing.JButton ButtonLineas;
    private javax.swing.JButton ButtonPuntos;
    private javax.swing.JButton ButtonTriangulo;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuEditar;
    private javax.swing.JMenu MenuHerramientas;
    private javax.swing.JMenuItem MenuItemAbrir;
    private javax.swing.JMenuItem MenuItemBorrar;
    private javax.swing.JMenuItem MenuItemGrosorLinea;
    private javax.swing.JMenuItem MenuItemGuardar;
    private javax.swing.JMenuItem MenuItemLimpiar;
    private javax.swing.JMenuItem MenuItemSalir;
    private javax.swing.JMenuItem MenuItemSeleccionarColorFondo;
    private javax.swing.JMenuItem MenuItemSeleccionarColorLinea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
